# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Agent.BuildDirectory)' 
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'appcenter-mnelli'
    appSlug: 'mnelli-org/testazureappbuild'
    appFile: '$(build.artifactStagingDirectory)/app-release-unsigned.apk'
    symbolsOption: 'Android'
    releaseNotesOption: 'input'
    destinationType: 'groups'
  
